/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  publishedAt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  externalUrl?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Skill = {
  _id: string;
  _type: "skill";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
  order?: number;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  organisation?: string;
  role?: string;
  kind?: "work" | "education";
  startDate?: string;
  endDate?: string;
  current?: boolean;
  location?: string;
  summary?: string;
  order?: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  clientName?: string;
  clientTitle?: string;
  permissionConfirmed?: boolean;
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  order?: number;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  order?: number;
  deliverables?: Array<string>;
  turnaround?: string;
  process?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  location?: string;
  seoTitle?: string;
  seoDescription?: string;
  shareImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroTitle?: string;
  heroEmphasis?: string;
  heroIntroduction?: string;
  primaryCtaLabel?: string;
  availability?: string;
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  featuredProject?: ProjectReference;
  workEyebrow?: string;
  workTitle?: string;
  aboutLabel?: string;
  aboutTitle?: string;
  aboutParagraphs?: Array<string>;
  facts?: Array<{
    value?: string;
    label?: string;
    _key: string;
  }>;
  servicesEyebrow?: string;
  servicesTitle?: string;
  contactEyebrow?: string;
  contactTitle?: string;
  contactCtaLabel?: string;
  email?: string;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  displayTitle?: string;
  slug?: Slug;
  category?: CategoryReference;
  year?: number;
  duration?: string;
  order?: number;
  summary?: string;
  videoUrl?: string;
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  client?: string;
  role?: string;
  tools?: Array<string>;
  brief?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  credits?: string;
  outcome?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  order?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Skill
  | Experience
  | Testimonial
  | Service
  | ProjectReference
  | SiteSettings
  | CategoryReference
  | Project
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/sanity/queries.ts
// Variable: HOME_QUERY
// Query: {  "site": *[_id == "siteSettings"][0]{    name,    role,    location,    seoTitle,    seoDescription,    shareImage {asset->{_id, url}, alt, hotspot, crop},    heroEyebrow,    heroTitle,    heroEmphasis,    heroIntroduction,    primaryCtaLabel,    availability,    portrait {asset->{_id, url}, alt, hotspot, crop},    "featuredProject": featuredProject->{      _id,      title,      displayTitle,      "slug": slug.current,      "category": category->title,      year,      duration,      order,      summary,      videoUrl,      vimeoId,      thumbnail {asset->{_id, url, metadata {lqip, dimensions}}, alt, hotspot, crop}    },    workEyebrow,    workTitle,    aboutLabel,    aboutTitle,    aboutParagraphs,    facts[]{_key, value, label},    servicesEyebrow,    servicesTitle,    contactEyebrow,    contactTitle,    contactCtaLabel,    email,    socialLinks[]{_key, label, url}  },  "projects": *[_type == "project"] | order(order asc, _createdAt asc){    _id,    title,    displayTitle,    "slug": slug.current,    "category": category->title,    year,    duration,    order,    summary,    videoUrl,    vimeoId,    thumbnail {asset->{_id, url, metadata {lqip, dimensions}}, alt, hotspot, crop}  },  "services": *[_type == "service"] | order(order asc, _createdAt asc){    _id,    title,    description,    order  }}
export type HOME_QUERY_RESULT = {
  site:
    | {
        name: null;
        role: null;
        location: null;
        seoTitle: null;
        seoDescription: null;
        shareImage: null;
        heroEyebrow: null;
        heroTitle: null;
        heroEmphasis: null;
        heroIntroduction: null;
        primaryCtaLabel: null;
        availability: null;
        portrait: null;
        featuredProject: null;
        workEyebrow: null;
        workTitle: null;
        aboutLabel: null;
        aboutTitle: null;
        aboutParagraphs: null;
        facts: null;
        servicesEyebrow: null;
        servicesTitle: null;
        contactEyebrow: null;
        contactTitle: null;
        contactCtaLabel: null;
        email: null;
        socialLinks: null;
      }
    | {
        name: null;
        role: string | null;
        location: null;
        seoTitle: null;
        seoDescription: null;
        shareImage: null;
        heroEyebrow: null;
        heroTitle: null;
        heroEmphasis: null;
        heroIntroduction: null;
        primaryCtaLabel: null;
        availability: null;
        portrait: null;
        featuredProject: null;
        workEyebrow: null;
        workTitle: null;
        aboutLabel: null;
        aboutTitle: null;
        aboutParagraphs: null;
        facts: null;
        servicesEyebrow: null;
        servicesTitle: null;
        contactEyebrow: null;
        contactTitle: null;
        contactCtaLabel: null;
        email: null;
        socialLinks: null;
      }
    | {
        name: null;
        role: null;
        location: null;
        seoTitle: null;
        seoDescription: null;
        shareImage: null;
        heroEyebrow: null;
        heroTitle: null;
        heroEmphasis: null;
        heroIntroduction: null;
        primaryCtaLabel: null;
        availability: null;
        portrait: {
          asset: {
            _id: string;
            url: string | null;
          } | null;
          alt: string | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        } | null;
        featuredProject: null;
        workEyebrow: null;
        workTitle: null;
        aboutLabel: null;
        aboutTitle: null;
        aboutParagraphs: null;
        facts: null;
        servicesEyebrow: null;
        servicesTitle: null;
        contactEyebrow: null;
        contactTitle: null;
        contactCtaLabel: null;
        email: null;
        socialLinks: null;
      }
    | {
        name: string | null;
        role: null;
        location: null;
        seoTitle: null;
        seoDescription: null;
        shareImage: null;
        heroEyebrow: null;
        heroTitle: null;
        heroEmphasis: null;
        heroIntroduction: null;
        primaryCtaLabel: null;
        availability: null;
        portrait: null;
        featuredProject: null;
        workEyebrow: null;
        workTitle: null;
        aboutLabel: null;
        aboutTitle: null;
        aboutParagraphs: null;
        facts: null;
        servicesEyebrow: null;
        servicesTitle: null;
        contactEyebrow: null;
        contactTitle: null;
        contactCtaLabel: null;
        email: null;
        socialLinks: null;
      }
    | {
        name: null;
        role: string | null;
        location: string | null;
        seoTitle: null;
        seoDescription: null;
        shareImage: null;
        heroEyebrow: null;
        heroTitle: null;
        heroEmphasis: null;
        heroIntroduction: null;
        primaryCtaLabel: null;
        availability: null;
        portrait: null;
        featuredProject: null;
        workEyebrow: null;
        workTitle: null;
        aboutLabel: null;
        aboutTitle: null;
        aboutParagraphs: null;
        facts: null;
        servicesEyebrow: null;
        servicesTitle: null;
        contactEyebrow: null;
        contactTitle: null;
        contactCtaLabel: null;
        email: null;
        socialLinks: null;
      }
    | {
        name: string | null;
        role: string | null;
        location: string | null;
        seoTitle: string | null;
        seoDescription: string | null;
        shareImage: {
          asset: {
            _id: string;
            url: string | null;
          } | null;
          alt: string | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        } | null;
        heroEyebrow: string | null;
        heroTitle: string | null;
        heroEmphasis: string | null;
        heroIntroduction: string | null;
        primaryCtaLabel: string | null;
        availability: string | null;
        portrait: {
          asset: {
            _id: string;
            url: string | null;
          } | null;
          alt: string | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        } | null;
        featuredProject: {
          _id: string;
          title: string | null;
          displayTitle: string | null;
          slug: string | null;
          category: string | null;
          year: number | null;
          duration: string | null;
          order: number | null;
          summary: string | null;
          videoUrl: string | null;
          vimeoId: null;
          thumbnail: {
            asset: {
              _id: string;
              url: string | null;
              metadata: {
                lqip: string | null;
                dimensions: SanityImageDimensions | null;
              } | null;
            } | null;
            alt: string | null;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
          } | null;
        } | null;
        workEyebrow: string | null;
        workTitle: string | null;
        aboutLabel: string | null;
        aboutTitle: string | null;
        aboutParagraphs: Array<string> | null;
        facts: Array<{
          _key: string;
          value: string | null;
          label: string | null;
        }> | null;
        servicesEyebrow: string | null;
        servicesTitle: string | null;
        contactEyebrow: string | null;
        contactTitle: string | null;
        contactCtaLabel: string | null;
        email: string | null;
        socialLinks: Array<{
          _key: string;
          label: string | null;
          url: string | null;
        }> | null;
      }
    | null;
  projects: Array<{
    _id: string;
    title: string | null;
    displayTitle: string | null;
    slug: string | null;
    category: string | null;
    year: number | null;
    duration: string | null;
    order: number | null;
    summary: string | null;
    videoUrl: string | null;
    vimeoId: null;
    thumbnail: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  }>;
  services: Array<{
    _id: string;
    title: string | null;
    description: string | null;
    order: number | null;
  }>;
};

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n  "site": *[_id == "siteSettings"][0]{\n    name,\n    role,\n    location,\n    seoTitle,\n    seoDescription,\n    shareImage {asset->{_id, url}, alt, hotspot, crop},\n    heroEyebrow,\n    heroTitle,\n    heroEmphasis,\n    heroIntroduction,\n    primaryCtaLabel,\n    availability,\n    portrait {asset->{_id, url}, alt, hotspot, crop},\n    "featuredProject": featuredProject->{\n      _id,\n      title,\n      displayTitle,\n      "slug": slug.current,\n      "category": category->title,\n      year,\n      duration,\n      order,\n      summary,\n      videoUrl,\n      vimeoId,\n      thumbnail {asset->{_id, url, metadata {lqip, dimensions}}, alt, hotspot, crop}\n    },\n    workEyebrow,\n    workTitle,\n    aboutLabel,\n    aboutTitle,\n    aboutParagraphs,\n    facts[]{_key, value, label},\n    servicesEyebrow,\n    servicesTitle,\n    contactEyebrow,\n    contactTitle,\n    contactCtaLabel,\n    email,\n    socialLinks[]{_key, label, url}\n  },\n  "projects": *[_type == "project"] | order(order asc, _createdAt asc){\n    _id,\n    title,\n    displayTitle,\n    "slug": slug.current,\n    "category": category->title,\n    year,\n    duration,\n    order,\n    summary,\n    videoUrl,\n    vimeoId,\n    thumbnail {asset->{_id, url, metadata {lqip, dimensions}}, alt, hotspot, crop}\n  },\n  "services": *[_type == "service"] | order(order asc, _createdAt asc){\n    _id,\n    title,\n    description,\n    order\n  }\n}': HOME_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
