import {defineArrayMember, defineField, defineType} from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Site settings',
  type: 'document',
  groups: [
    {name: 'identity', title: 'Identity & SEO', default: true},
    {name: 'hero', title: 'Hero'},
    {name: 'work', title: 'Work section'},
    {name: 'about', title: 'About'},
    {name: 'services', title: 'Services'},
    {name: 'contact', title: 'Contact'},
  ],
  fields: [
    defineField({name: 'name', title: 'Name', type: 'string', group: 'identity', validation: (rule) => rule.required()}),
    defineField({name: 'role', title: 'Professional role', type: 'string', group: 'identity', validation: (rule) => rule.required()}),
    defineField({name: 'location', title: 'Location', type: 'string', group: 'identity'}),
    defineField({name: 'seoTitle', title: 'Browser and search title', type: 'string', group: 'identity', validation: (rule) => rule.required().max(60)}),
    defineField({name: 'seoDescription', title: 'Search description', type: 'text', rows: 3, group: 'identity', validation: (rule) => rule.required().max(160)}),
    defineField({
      name: 'shareImage',
      title: 'Social share image',
      type: 'image',
      group: 'identity',
      options: {hotspot: true},
      fields: [defineField({name: 'alt', title: 'Alternative text', type: 'string'})],
    }),
    defineField({name: 'heroEyebrow', title: 'Hero eyebrow', type: 'string', group: 'hero'}),
    defineField({name: 'heroTitle', title: 'Hero title', description: 'Use a line break where the title should wrap.', type: 'text', rows: 2, group: 'hero', validation: (rule) => rule.required()}),
    defineField({name: 'heroEmphasis', title: 'Highlighted word', type: 'string', group: 'hero', validation: (rule) => rule.required()}),
    defineField({name: 'heroIntroduction', title: 'Introduction', type: 'text', rows: 3, group: 'hero', validation: (rule) => rule.required()}),
    defineField({name: 'primaryCtaLabel', title: 'Primary button label', type: 'string', group: 'hero'}),
    defineField({name: 'availability', title: 'Availability message', type: 'string', group: 'hero'}),
    defineField({
      name: 'portrait',
      title: 'Portrait',
      type: 'image',
      group: 'hero',
      options: {hotspot: true},
      fields: [defineField({name: 'alt', title: 'Alternative text', type: 'string', validation: (rule) => rule.required().warning('Alternative text helps screen-reader users.')})],
    }),
    defineField({name: 'featuredProject', title: 'Featured project', type: 'reference', to: [{type: 'project'}], group: 'work'}),
    defineField({name: 'workEyebrow', title: 'Work eyebrow', type: 'string', group: 'work'}),
    defineField({name: 'workTitle', title: 'Work heading', description: 'Use a line break where the heading should wrap.', type: 'text', rows: 2, group: 'work'}),
    defineField({name: 'aboutLabel', title: 'About label', type: 'string', group: 'about'}),
    defineField({name: 'aboutTitle', title: 'About heading', type: 'string', group: 'about'}),
    defineField({name: 'aboutParagraphs', title: 'About paragraphs', type: 'array', group: 'about', of: [defineArrayMember({type: 'text', rows: 4})]}),
    defineField({
      name: 'facts',
      title: 'About facts',
      type: 'array',
      group: 'about',
      of: [defineArrayMember({type: 'object', fields: [
        defineField({name: 'value', title: 'Value', type: 'string', validation: (rule) => rule.required()}),
        defineField({name: 'label', title: 'Label', type: 'string', validation: (rule) => rule.required()}),
      ], preview: {select: {title: 'value', subtitle: 'label'}}})],
    }),
    defineField({name: 'servicesEyebrow', title: 'Services eyebrow', type: 'string', group: 'services'}),
    defineField({name: 'servicesTitle', title: 'Services heading', description: 'Use a line break where the heading should wrap.', type: 'text', rows: 2, group: 'services'}),
    defineField({name: 'contactEyebrow', title: 'Contact eyebrow', type: 'string', group: 'contact'}),
    defineField({name: 'contactTitle', title: 'Contact heading', description: 'Use a line break where the heading should wrap.', type: 'text', rows: 2, group: 'contact'}),
    defineField({name: 'contactCtaLabel', title: 'Contact link label', type: 'string', group: 'contact'}),
    defineField({name: 'email', title: 'Contact email', type: 'string', group: 'contact', validation: (rule) => rule.required().email()}),
    defineField({
      name: 'socialLinks',
      title: 'Social links',
      type: 'array',
      group: 'contact',
      of: [defineArrayMember({type: 'object', fields: [
        defineField({name: 'label', title: 'Label', type: 'string', validation: (rule) => rule.required()}),
        defineField({name: 'url', title: 'URL', type: 'url', validation: (rule) => rule.required().uri({scheme: ['http', 'https']})}),
      ], preview: {select: {title: 'label', subtitle: 'url'}}})],
    }),
  ],
  preview: {select: {title: 'name', subtitle: 'role'}},
})
